name: Go CI Pipeline

on:
  # 1. On push to main branch
  push:
    branches: [ "main" ]
  # 2. On pull request to main branch
  pull_request:
    branches: [ "main" ]

jobs:
  quality-check:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      # 1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      # 3. Modern Linting (fmt, lint, vet, shadow)
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: src
          # only-new-issues: true 

      # 4. Modern Linting (fmt, lint, vet, shadow)
      #- name: Run staticcheck
      #  uses: honnef.co/go/tools/cmd/staticcheck@latest
      #  with:
      #    version: latest   

      # 5. Run Tests
      - name: Run Tests
        run: go test -v -race ./...

      # 6. Verify Build 
      - name: Verify Build
        run: go build -v -o /dev/null ./cmd/json2bin-parser/